sudo: true
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
#   - CI=false npm run build

after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

branches:
  only:
  - inventory
# language: node_js
# node_js:
#   - "stable"
# cache:
#   directories:
#     - ~/.npm
# before_script:
#   - npm install -g npm@latest
# script:
#   - npm ci
#   - npx jest --ci